# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: Matomo Tracking

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/DIE-Bonn/MatomoTracking

# A brief description of what your plugin is doing.
summary: This plugin is used to enhance or replace the client-side javascript-based visitor tracking with Matomo by a server-side tracking strategy. This concept is able to bypass javascript-blocking browser addons to increase the accuracy of visitor tracking and providing more comprehensive tracking results.

iconPath: .assets/matomo_tracking_logo.png

bannerPath: .assets/matomo_tracking_logo.png

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  matomoURL: "https://matomo-staging.die-bonn.de/matomo.php"
  domains:
    "ppa.die-bonn.de":
      trackingEnabled: true
      idSite: 123
      excludedPaths:
        - "/admin/*"
        - "\\.\\w{1,5}(\\?.+)?$"
      includedPaths:
        - "\\.(php|aspx)(\\?.*)?$"
    "kansas-suche.de":
      trackingEnabled: false
      idSite: 456
